project:
  type: website

website:
  description: "MADS - Multi-Agent Distributed System"
  site-url: "https://mads-net.github.io"
  draft-mode: unlinked
  back-to-top-navigation: true
  reader-mode: true
  page-footer: 
    left: "Paolo Bosetti, [BY-NC-SA4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)" 
  navbar:
    left:
      - href: guides.qmd
        text: "Guides"
      - href: why.qmd
        text: "Why MADS?"
      - href: who_is_using.qmd
        text: "Use cases"
      - text: "Presentations"
        menu:
          - href: presentations/intro.qmd
            text: "{{< logo >}} Intro"
    right:
      - href: about.qmd
        text: "About"
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/pbosetti/mads
          - text: Issues
            href: https://github.com/pbosetti/MADS/issues
          - text: Plugins
            href:  https://github.com/MADS-Net

format:
  html:
    toc: true
    email-obfuscation: "javascript"
    theme: 
      - flatly
      - brand
      - custom.scss
  revealjs:
    theme: [default, presentations/slides.scss]
    width: 1280
    height: 720
    margin: 0.1
    slide-number: true
    code-line-numbers: true
    code-annotations: below
    preview-links: auto
    chalkboard: true
    footer: "MADS --- [https://mads-net.github.io](https://mads-net.github.io)"
    fig-width: 5
    fig-height: 4
    fig-dpi: 300
    touch: true
    email-obfuscation: javascript
    pdf-separate-fragments: true
    link-external-icon: true
    lang: en-EN
