project:
  type: website

website:
  description: "MADS - Multi-Agent Distributed System"
  site-url: "https://mads-net.github.io"
  draft-mode: unlinked
  back-to-top-navigation: true
  reader-mode: true
  google-analytics: "G-L37VBCVVQW"
  cookie-consent:
    type: express
    style: simple
    palette: light
  announcement:
    content: "Don't miss the new [MADSCode extension]{style=font-weight:bold} for Visual Studio Code! [Learn more {{< bi link >}}](https://marketplace.visualstudio.com/items?itemName=MADS-Net.madscode)"
    position: below-navbar   # or below-navbar
    type: warning           # primary, secondary, success, warning, danger
    dismissable: true
  page-footer: 
    left: "Paolo Bosetti, [BY-NC-SA4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)" 
  navbar:
    left:
      - text: "Introduction"
        menu:
        - href: start.qmd
          text: "Start here"
        - href: why.qmd
          text: "Why MADS?"
        - href: interfaces.qmd
          text: "Interfaces"
        - href: who_is_using.qmd
          text: "Use cases"
      - href: manual
        text: "Documentation"
      - text: "Commands"
        menu:
        - href: manual/mads.qmd
          text: "mads command"
        - href: manual/broker.qmd
          text: "Broker"
        - href: manual/plugin.qmd
          text: "Plugin"
        - href: manual/source-filter-sink.qmd
          text: "Source / Filter / Sink"
        - href: manual/logger.qmd
          text: "Logger"
        - href: manual/feedback-perf_assess.qmd
          text: "Feedback / Perf Assess"
        - href: manual/inspect_plugin.qmd
          text: "Inspect Plugin"
        - href: manual/federate.qmd
          text: "Federate"
        - href: manual/fsm.qmd
          text: "FSM"
        - href: manual/package.qmd
          text: "Package"
        - href: manual/dealer-worker.qmd
          text: "Dealer / Worker"
        - href: manual/rust-loaders.qmd
          text: "Rust Loaders"
      - text: "Concepts"
        menu:
        - href: manual/network-discovery.qmd
          text: "Network discovery"
        - href: manual/message-routing.qmd
          text: "Message routing and topics"
        - href: manual/plugins-extensions.qmd
          text: "Plugins and extensions"
        - href: manual/timing-scheduling.qmd
          text: "Timing and scheduling"
        - href: manual/message-queues.qmd
          text: "Message queues"
        - href: manual/databases-storage.qmd
          text: "Databases and data storage"
        - href: manual/cryptography-security.qmd
          text: "Cryptography and security"
      - href: guides.qmd
        text: "Guides"
      - text: "Presentations"
        menu:
          - href: presentations/intro.qmd
            text: "{{< logo >}} Intro"
    right:
      - href: https://git.new/MADS
        text: "{{< bi cloud-arrow-down-fill >}} Get MADS"
      - href: about.qmd
        text: "{{< bi question-circle-fill >}} About"
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/pbosetti/mads
          - text: Issues
            href: https://github.com/pbosetti/MADS/issues
          - text: Plugins
            href:  https://github.com/MADS-Net

format:
  html:
    toc: true
    email-obfuscation: "javascript"
    theme: 
      - flatly
      - brand
      - custom.scss
  revealjs:
    theme: [default, presentations/slides.scss]
    width: 1280
    height: 720
    margin: 0.1
    slide-number: true
    code-line-numbers: true
    code-annotations: below
    controls: true
    preview-links: auto
    chalkboard: true
    footer: "MADS --- [https://mads-net.github.io](https://mads-net.github.io)"
    fig-width: 5
    fig-height: 4
    fig-dpi: 300
    touch: true
    email-obfuscation: javascript
    pdf-separate-fragments: true
    link-external-icon: true
    lang: en-EN
