<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Paolo Bosetti">
<meta name="dcterms.date" content="2026-09-25">

<title>Time and time synchronization</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-3c3f1368ed8db972a012dae01a8e5220.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-97e28f47ad423cfcb72627c3f906fd98.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-3c3f1368ed8db972a012dae01a8e5220.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-333e99d084c2ffcec8e6d96540d279c4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-580cd51fbb4f3c7d95b8bb74838632fa.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-333e99d084c2ffcec8e6d96540d279c4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/bootstrap-icons-1.11.1/all.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-L37VBCVVQW"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-L37VBCVVQW', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"en"
  });
});
</script> 
  


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/logo_white.png" alt="" class="navbar-logo light-content">
    <img src="../images/logo_white.png" alt="" class="navbar-logo dark-content">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-introduction" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Introduction</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-introduction">    
        <li>
    <a class="dropdown-item" href="../start.html">
 <span class="dropdown-text">Start here</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../why.html">
 <span class="dropdown-text">Why MADS?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../interfaces.html">
 <span class="dropdown-text">Interfaces</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../who_is_using.html">
 <span class="dropdown-text">Use cases</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../flyer.pdf">
 <span class="dropdown-text">Flyer</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../manual"> 
<span class="menu-text">Documentation</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-commands" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Commands</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-commands">    
        <li>
    <a class="dropdown-item" href="../manual/mads.html">
 <span class="dropdown-text">mads command</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/broker.html">
 <span class="dropdown-text">Broker</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/plugin.html">
 <span class="dropdown-text">Plugin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/source-filter-sink.html">
 <span class="dropdown-text">Source / Filter / Sink</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/logger.html">
 <span class="dropdown-text">Logger</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/feedback-perf_assess.html">
 <span class="dropdown-text">Feedback / Perf Assess</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/inspect_plugin.html">
 <span class="dropdown-text">Inspect Plugin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/federate.html">
 <span class="dropdown-text">Federate</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/fsm.html">
 <span class="dropdown-text">FSM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/package.html">
 <span class="dropdown-text">Package</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/dealer-worker.html">
 <span class="dropdown-text">Dealer / Worker</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/rust-loaders.html">
 <span class="dropdown-text">Rust Loaders</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-concepts" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Concepts</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-concepts">    
        <li>
    <a class="dropdown-item" href="../manual/network-discovery.html">
 <span class="dropdown-text">Network discovery</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/message-routing.html">
 <span class="dropdown-text">Message routing and topics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/plugins-extensions.html">
 <span class="dropdown-text">Plugins and extensions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/timing-scheduling.html">
 <span class="dropdown-text">Timing and scheduling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/message-queues.html">
 <span class="dropdown-text">Message queues</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/databases-storage.html">
 <span class="dropdown-text">Databases and data storage</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../manual/cryptography-security.html">
 <span class="dropdown-text">Cryptography and security</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../guides.html"> 
<span class="menu-text">Guides</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-presentations" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Presentations</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-presentations">    
        <li>
    <a class="dropdown-item" href="../presentations/intro.html">
 <span class="dropdown-text"><img src="../images/logo.svg" style="height: 0.9em; vertical-align: -0.125em; margin: 0; padding: 0; filter: drop-shadow(2px 2px 2px rgba(0,0,0,0.2));"> Intro</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentations/gorini.html">
 <span class="dropdown-text">Scuola Gorini 2026</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://git.new/MADS"> 
<span class="menu-text"><i class="bi-cloud-arrow-down-fill " style="" role="img" aria-hidden="true"></i> Get MADS</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text"><i class="bi-question-circle-fill " style="" role="img" aria-hidden="true"></i> About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-github" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-github">    
        <li>
    <a class="dropdown-item" href="https://github.com/pbosetti/mads">
 <span class="dropdown-text">Source Code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/pbosetti/MADS/issues">
 <span class="dropdown-text">Issues</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/MADS-Net">
 <span class="dropdown-text">Plugins</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <div id="quarto-announcement" data-announcement-id="bac4023a3167daaad50509f0325463c0" class="alert alert-warning hidden"><div class="quarto-announcement-content">
<p>Don’t miss the new <span style="font-weight:bold">MADSCode extension</span> for Visual Studio Code! <a href="https://marketplace.visualstudio.com/items?itemName=MADS-Net.madscode">Learn more <i class="bi-link " style="" role="img" aria-hidden="true"></i></a></p>
</div><i class="bi bi-x-lg quarto-announcement-action"></i></div>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#why-time-matters" id="toc-why-time-matters" class="nav-link active" data-scroll-target="#why-time-matters">Why time matters</a></li>
  <li><a href="#how-mads-puts-time-into-a-message" id="toc-how-mads-puts-time-into-a-message" class="nav-link" data-scroll-target="#how-mads-puts-time-into-a-message">How MADS puts time into a message</a>
  <ul class="collapse">
  <li><a href="#timecode-caveats" id="toc-timecode-caveats" class="nav-link" data-scroll-target="#timecode-caveats">Timecode caveats</a></li>
  </ul></li>
  <li><a href="#the-problem-every-computer-has-its-own-clock" id="toc-the-problem-every-computer-has-its-own-clock" class="nav-link" data-scroll-target="#the-problem-every-computer-has-its-own-clock">The problem: every computer has its own clock</a></li>
  <li><a href="#the-classic-fix-ntp" id="toc-the-classic-fix-ntp" class="nav-link" data-scroll-target="#the-classic-fix-ntp">The classic fix: NTP</a>
  <ul class="collapse">
  <li><a href="#when-ntp-is-not-enough" id="toc-when-ntp-is-not-enough" class="nav-link" data-scroll-target="#when-ntp-is-not-enough">When NTP is not enough</a></li>
  </ul></li>
  <li><a href="#whats-new-in-mads-v2.5.0" id="toc-whats-new-in-mads-v2.5.0" class="nav-link" data-scroll-target="#whats-new-in-mads-v2.5.0">What’s new in MADS v2.5.0</a>
  <ul class="collapse">
  <li><a href="#step-1-each-agent-measures-its-offset-automatic" id="toc-step-1-each-agent-measures-its-offset-automatic" class="nav-link" data-scroll-target="#step-1-each-agent-measures-its-offset-automatic">Step 1 — Each agent measures its offset (automatic)</a></li>
  <li><a href="#step-2-agents-on-the-same-computer-share-one-measurement" id="toc-step-2-agents-on-the-same-computer-share-one-measurement" class="nav-link" data-scroll-target="#step-2-agents-on-the-same-computer-share-one-measurement">Step 2 — Agents on the same computer share one measurement</a></li>
  <li><a href="#seeing-the-whole-network-mads-top" id="toc-seeing-the-whole-network-mads-top" class="nav-link" data-scroll-target="#seeing-the-whole-network-mads-top">Seeing the whole network: <code>mads top</code></a>
  <ul class="collapse">
  <li><a href="#at-a-glance-the-host-clock-skew-section" id="toc-at-a-glance-the-host-clock-skew-section" class="nav-link" data-scroll-target="#at-a-glance-the-host-clock-skew-section">At a glance: the <em>Host clock skew</em> section</a></li>
  <li><a href="#in-detail-mads-top---probe" id="toc-in-detail-mads-top---probe" class="nav-link" data-scroll-target="#in-detail-mads-top---probe">In detail: <code>mads top --probe</code></a></li>
  </ul></li>
  <li><a href="#step-3-correct-the-timestamps-optional" id="toc-step-3-correct-the-timestamps-optional" class="nav-link" data-scroll-target="#step-3-correct-the-timestamps-optional">Step 3 — Correct the timestamps (optional)</a></li>
  <li><a href="#keeping-up-with-drift" id="toc-keeping-up-with-drift" class="nav-link" data-scroll-target="#keeping-up-with-drift">Keeping up with drift</a></li>
  <li><a href="#agents-that-cant-reach-the-broker-directly" id="toc-agents-that-cant-reach-the-broker-directly" class="nav-link" data-scroll-target="#agents-that-cant-reach-the-broker-directly">Agents that can’t reach the broker directly</a></li>
  <li><a href="#settings-reference" id="toc-settings-reference" class="nav-link" data-scroll-target="#settings-reference">Settings reference</a></li>
  </ul></li>
  <li><a href="#which-setup-should-i-use" id="toc-which-setup-should-i-use" class="nav-link" data-scroll-target="#which-setup-should-i-use">Which setup should I use?</a></li>
  <li><a href="#good-to-know" id="toc-good-to-know" class="nav-link" data-scroll-target="#good-to-know">Good to know</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Time and time synchronization</h1>
  <div class="quarto-categories">
    <div class="quarto-category">intermediate</div>
    <div class="quarto-category">timing</div>
    <div class="quarto-category">OS</div>
    <div class="quarto-category">setup</div>
  </div>
  </div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Paolo Bosetti </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Trento
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 25, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 25, 2026</p>
    </div>
  </div>
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>MADS collects and transforms data from a network of distributed devices: synchronizing the timestamps is of paramount importance for having a quality database.</p>
  </div>
</div>


</header>


<section id="why-time-matters" class="level1">
<h1>Why time matters</h1>
<p>A MADS network usually spans several computers: a Raspberry Pi reading sensors, a workstation running a controller, a server storing everything in a database. When you look at the data afterwards, you want to answer questions like:</p>
<ul>
<li><em>did the temperature rise before or after the motor started?</em></li>
<li><em>how long did the controller take to react to that alarm?</em></li>
<li><em>what were all sensors reading at 10:53:18?</em></li>
</ul>
<p>To answer them, every message must carry the time at which it was produced, <strong>and those times must be comparable across computers</strong>. This guide explains how MADS writes time into messages, why different computers rarely agree on what time it is, and how MADS v2.5.0 helps you measure and fix the disagreement.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Short version
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Every message gets a <code>timestamp</code> and a <code>timecode</code>, read from the clock of the computer that <strong>sent</strong> it.</li>
<li>Computer clocks drift apart. The standard fix is <strong>NTP</strong>, a service that keeps a computer’s clock on time.</li>
<li>From <strong>v2.5.0</strong>, every agent automatically measures how far its clock is from the broker computer’s clock. Run <code>mads top --probe</code> to see it.</li>
<li>If you can’t (or don’t want to) set up NTP everywhere, add <code>clock_correction = true</code> to the <code>[agents]</code> section of <code>mads.ini</code>: all timestamps will then be aligned to the broker’s clock.</li>
</ul>
</div>
</div>
</section>
<section id="how-mads-puts-time-into-a-message" class="level1">
<h1>How MADS puts time into a message</h1>
<p>Every time an agent publishes a message, MADS adds three fields to it (unless the message already has them):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">{</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"data"</span><span class="fu">:</span> <span class="fu">{</span> <span class="dt">"T"</span><span class="fu">:</span> <span class="fl">21.4</span> <span class="fu">},</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"timestamp"</span><span class="fu">:</span> <span class="fu">{</span> <span class="dt">"$date"</span><span class="fu">:</span> <span class="st">"2025-07-11T10:53:18.716+0200"</span> <span class="fu">},</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"timecode"</span><span class="fu">:</span> <span class="fl">39198.68</span><span class="fu">,</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"hostname"</span><span class="fu">:</span> <span class="st">"computer-A"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl>
<dt><code>timestamp</code></dt>
<dd>
The date and time, down to the millisecond, in the standard <em>ISO 8601</em> format. The final <code>+0200</code> is the time zone of the sending computer, so the timestamp identifies one exact instant no matter where it was produced. The odd-looking <code>{"$date": ...}</code> wrapper lets MongoDB store it as a real date, so you can search and sort by it. This is the field used by the loggers and by <a href="../guides/replay.html">the replay agent</a>.
</dd>
<dt><code>timecode</code></dt>
<dd>
The number of seconds since <strong>local midnight</strong>, rounded to a <em>frame</em>. It is a plain number, which makes it convenient for plots and for lining up samples from different sources. The frame length is set by <code>timecode_fps</code> in the <code>[agents]</code> section of <code>mads.ini</code>: with the default of 25 frames per second, timecodes are multiples of 40 ms. In the example, 39198.68 s is 10:53:18.68.
</dd>
<dt><code>hostname</code></dt>
<dd>
The name of the computer that sent the message.
</dd>
</dl>
<p>The important point is <strong>where</strong> these values come from:</p>
<p><img src="images/timing_stamp.svg" class="img-fluid" style="width:100.0%" alt="A source agent on computer A sends a message through the broker to a logger. The timestamp, timecode and hostname fields are added by the source agent, using computer A's clock. The broker and the logger do not change them."></p>
<p>The time is read <strong>from the clock of the computer that sends the message</strong>, at the moment the message is sent. The broker only forwards the message, and the logger stores it as it arrives. Neither of them changes the time.</p>
<p>So if computer A’s clock is wrong, every message from computer A carries a wrong time, and nothing further along the chain will notice.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If your plugin or script already puts a <code>timestamp</code> or <code>timecode</code> field in the message, MADS keeps yours. This is useful when your device has its own precise acquisition time, such as a data acquisition board with a hardware clock. It also means that you are responsible for that time being correct.</p>
</div>
</div>
<section id="timecode-caveats" class="level2">
<h2 class="anchored" data-anchor-id="timecode-caveats">Timecode caveats</h2>
<p>The timecode is handy but has three limits you should know about:</p>
<ul>
<li><strong>It restarts at midnight.</strong> A recording spanning midnight goes from 86399.96 back to 0. Use <code>timestamp</code> when you need the date too.</li>
<li><strong>It uses local time.</strong> Two computers set to different time zones produce timecodes that are hours apart for the same instant. Set all MADS computers to the same time zone, or use <code>timestamp</code>, which includes the time zone.</li>
<li><strong>It is rounded to the frame.</strong> At 25 fps, two messages sent 10 ms apart can have the same timecode. If you need finer resolution, use <code>timestamp</code> or raise <code>timecode_fps</code>.</li>
</ul>
</section>
</section>
<section id="the-problem-every-computer-has-its-own-clock" class="level1">
<h1>The problem: every computer has its own clock</h1>
<p>Every computer keeps time with a small quartz crystal. These crystals are cheap and good, but not perfect: a typical one gains or loses a few seconds per day, and the exact amount changes with temperature. Some situations make it worse:</p>
<ul>
<li>A <strong>Raspberry Pi</strong> has no battery-backed clock. When it boots without a network connection, it starts from the last time it remembers, which can be hours or days in the past.</li>
<li>A <strong>virtual machine or container host</strong> that has been suspended can wake up with its clock stuck at the moment it was suspended.</li>
<li>A clock that was <strong>set by hand</strong> is usually off by a few seconds from the start.</li>
</ul>
<p>Left alone, two computers that agree today will disagree by seconds after a few weeks. For a MADS network this matters a lot, because it changes the story your data tells:</p>
<p><img src="images/timing_drift.svg" class="img-fluid" style="width:100.0%" alt="Two timelines. On the first one, labelled what really happened, the button press on computer A happens at 10:00:00.000 and the motor start on computer B at 10:00:00.200. On the second one, labelled what the database says, computer A's clock is half a second ahead, so the button press is recorded at 10:00:00.500, after the motor start."></p>
<p>Here, computer A’s clock is only half a second ahead, and the database now says the motor started <em>before</em> the button was pressed. With the same error, a measured reaction time could come out <em>negative</em>, or two signals that should be in step could appear shifted. You will not get an error message: the data simply looks wrong, or worse, looks right but isn’t.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nothing in the data itself tells you whether the clocks were in agreement. You have to check it <strong>while the system is running</strong>, because once the data is in the database it is usually too late to find out.</p>
</div>
</div>
</section>
<section id="the-classic-fix-ntp" class="level1">
<h1>The classic fix: NTP</h1>
<p>The standard solution, used by nearly every computer connected to the internet, is the <strong>Network Time Protocol (NTP)</strong>. A small service on each computer regularly asks a <em>time server</em> what time it is, measures how long the answer took to arrive, and gently adjusts the local clock so it stays in step. With a good setup, computers on the same local network agree to within a millisecond or better. Over the internet, the agreement is within a few milliseconds.</p>
<p>Most operating systems enable NTP by default, <strong>as long as the computer can reach a time server</strong>. This is how to check it:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Linux (and Raspberry Pi OS)</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">macOS</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">Windows</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">timedatectl</span> status</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Look for <code>System clock synchronized: yes</code> and <code>NTP service: active</code>. If your system uses <em>chrony</em> (common on recent distributions), you can get more detail, including the current error, with:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">chronyc</span> tracking</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The <code>System time</code> line tells you how far the clock is from the NTP time.</p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>NTP is enabled in <em>System Settings → General → Date &amp; Time → Set time and date automatically</em>. To see the current error against a time server:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="ex">sntp</span> time.apple.com</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The first number printed is the difference in seconds between your clock and the server’s clock.</p>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>NTP is enabled in <em>Settings → Time &amp; language → Date &amp; time → Set time automatically</em>. To check its status from a terminal:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>w32tm <span class="op">/</span>query <span class="op">/</span>status</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>and to force an immediate update (from an administrator terminal):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>w32tm <span class="op">/</span>resync</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<section id="when-ntp-is-not-enough" class="level2">
<h2 class="anchored" data-anchor-id="when-ntp-is-not-enough">When NTP is not enough</h2>
<p>NTP works well, but in real MADS installations you often hit one of these cases:</p>
<ul>
<li><p><strong>The network is isolated.</strong> Machine networks in labs and factories are often cut off from the internet, so no public time server can be reached. You can turn one of your computers into a local time server. The broker computer is a natural choice. For example, with chrony on Linux, add these two lines to <code>/etc/chrony/chrony.conf</code> on the broker computer and restart chrony:</p>
<pre><code>allow 192.168.1.0/24   # the address range of your MADS network
local stratum 10       # keep serving time even with no internet</code></pre>
<p>Then point the other computers to it. However, this needs administrator access and some care on every machine.</p></li>
<li><p><strong>You can’t configure some of the devices.</strong> This includes embedded boards, computers managed by someone else, or a colleague’s laptop that joins for one experiment.</p></li>
<li><p><strong>You don’t know whether it is working.</strong> NTP runs silently. Each computer can say whether <em>it</em> thinks it is synchronized, but nothing tells you whether the whole MADS network actually agrees <em>right now</em>.</p></li>
</ul>
<p>This is where MADS v2.5.0 comes in.</p>
</section>
</section>
<section id="whats-new-in-mads-v2.5.0" class="level1">
<h1>What’s new in MADS v2.5.0</h1>
<p>Starting with v2.5.0, MADS itself can <strong>measure</strong>, <strong>show</strong> and, if you ask it to, <strong>correct</strong> the differences between the clocks of your computers. You don’t need to write any code for this, and in most cases you don’t need to change any settings either.</p>
<p>The reference clock is always <strong>the clock of the computer running the broker</strong>. It doesn’t matter whether that clock is exactly right. What matters is that all agents are compared against the same clock, so that their timestamps can be compared with each other.</p>
<section id="step-1-each-agent-measures-its-offset-automatic" class="level2">
<h2 class="anchored" data-anchor-id="step-1-each-agent-measures-its-offset-automatic">Step 1 — Each agent measures its offset (automatic)</h2>
<p>When an agent starts, it contacts the broker to download its settings. Since v2.5.0, it also runs a short time check with the broker. Five times in a row, it asks the broker “what time is it?” and notes when the question left and when the answer came back:</p>
<p><img src="images/timing_exchange.svg" class="img-fluid" style="width:100.0%" alt="Timing diagram between an agent and the broker. The agent sends a request at time t1, as read on its own clock. The broker receives it at t2 and replies at t3, both read on the broker's clock. The agent receives the reply at t4. From the four times, the agent computes the round-trip delay and the clock offset."></p>
<p>The exchange produces four times. Two are read on the agent’s clock and two on the broker’s clock. From these, the agent works out two things:</p>
<ul>
<li>the <strong>delay</strong>: how long the message spent travelling on the network, there and back</li>
<li>the <strong>offset</strong>: how many milliseconds must be added to the agent’s clock to read the same time as the broker’s clock</li>
</ul>
<p>This is the same method NTP uses. Out of the five attempts, MADS keeps the one with the shortest delay, because a fast round trip leaves less room for error.</p>
<p>The result is printed in the agent’s startup summary:</p>
<pre><code>  Timecode FPS:     25
  Timecode offset:  0 s
  Clock domain:     raspberrypi
  Clock offset:     42.017 ms (broker, 0 hops, delay 0.412 ms, ref sensor_1:1)</code></pre>
<p>To read these lines:</p>
<ul>
<li><strong>Clock offset: 42.017 ms</strong> means this computer’s clock is about 42 ms <em>behind</em> the broker’s clock. A negative number means it is <em>ahead</em>.</li>
<li><strong>delay 0.412 ms</strong> is the network round-trip time. On a wired local network this is typically well below a millisecond. On Wi-Fi it can be a few milliseconds.</li>
<li><strong>Clock domain</strong> and <strong>ref</strong> are explained in the next step.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Measuring does not change anything.</strong> By default, MADS only measures and reports the offset. Your computer’s clock is never touched, and the timestamps in your messages are exactly as they were before v2.5.0. Correcting the timestamps is a separate choice (see <a href="#step-3-correct-the-timestamps-optional">Step 3</a>).</p>
</div>
</div>
</section>
<section id="step-2-agents-on-the-same-computer-share-one-measurement" class="level2">
<h2 class="anchored" data-anchor-id="step-2-agents-on-the-same-computer-share-one-measurement">Step 2 — Agents on the same computer share one measurement</h2>
<p>All agents running on the same computer read the same clock, so they should all have the <strong>same</strong> offset. If each agent measured on its own, they would get slightly different numbers because of network noise. Their corrected timestamps would then disagree by a fraction of a millisecond, for no reason.</p>
<p>To avoid this, agents on the same computer form a <strong>clock domain</strong>. Every few seconds, each agent tells the others in its domain what it measured, and they all adopt the same measurement: the one with the shortest network delay. No configuration is needed.</p>
<p><img src="images/timing_domains.svg" class="img-fluid" style="width:100.0%" alt="The broker computer at the top holds the reference clock. Below it, a Raspberry Pi with three agents forms one clock domain: one agent measures its offset against the broker and shares the result, so all three show +42.0 ms. A workstation with two agents forms a second clock domain, where all agents show −3.1 ms."></p>
<p>The <code>ref</code> value in the startup summary, for example <code>sensor_1:1</code>, says which agent’s measurement is being used. All agents in the same domain should show the same <code>ref</code>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>On Linux, the clock domain is identified by the running system kernel rather than by the computer name. This means that several <strong>Docker containers</strong> on the same machine, which have different names but share the same clock, are correctly treated as one domain. On macOS and Windows, the computer name is used.</p>
</div>
</div>
</section>
<section id="seeing-the-whole-network-mads-top" class="level2">
<h2 class="anchored" data-anchor-id="seeing-the-whole-network-mads-top">Seeing the whole network: <code>mads top</code></h2>
<p>The <code>mads top</code> command (see <code>man mads-top</code>) shows the live traffic on your MADS network. Since v2.5.0 it helps you check the clocks in two ways.</p>
<section id="at-a-glance-the-host-clock-skew-section" class="level3">
<h3 class="anchored" data-anchor-id="at-a-glance-the-host-clock-skew-section">At a glance: the <em>Host clock skew</em> section</h3>
<p>In its normal mode, <code>mads top</code> adds a <strong>Host clock skew</strong> section below the topic table. For each computer that is sending messages, it shows the difference between the time written in the messages and the time on the computer where you run <code>mads top</code>:</p>
<pre><code>  Host clock skew (passive, vs. this machine's local time -- see 'mads top --probe' for a real measurement)
    raspberrypi           +41.3ms
    workstation           -3.3ms</code></pre>
<p>This costs nothing, as it only reads messages that are already travelling on the network, and it works with agents of any MADS version. However, it mixes the clock difference with the network delay, so treat it as a rough indicator:</p>
<ul>
<li>a few milliseconds: fine, that’s just the network</li>
<li>hundreds of milliseconds or more: the clocks disagree, and it’s time to look closer</li>
</ul>
</section>
<section id="in-detail-mads-top---probe" class="level3">
<h3 class="anchored" data-anchor-id="in-detail-mads-top---probe">In detail: <code>mads top --probe</code></h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="ex">mads</span> top <span class="at">--probe</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>In this mode, <code>mads top</code> asks every agent on the network to report its current offset, and displays them grouped by clock domain:</p>
<pre><code>mads top --probe  5 responder(s)  link: up   (press q to quit)

  (this agent)  domain laptop  offset +1.2ms  (broker, 0 hops, ref top@8812:1)

  DOMAIN raspberrypi
    sensor_1          raspberrypi     +42.0ms     broker  0 hops  delay 3.1ms
    sensor_2          raspberrypi     +42.0ms     broker  0 hops  delay 2.8ms
    filter            raspberrypi     +42.0ms     broker  0 hops  delay 3.4ms
  DOMAIN workstation
    logger            workstation     -3.1ms      broker  0 hops  delay 1.9ms
    controller        workstation     -3.1ms      broker  0 hops  delay 2.2ms</code></pre>
<p>What to look for:</p>
<ul>
<li><strong>Within a domain, all offsets are identical.</strong> If they differ and stay different, something is wrong, for example agents that cannot hear each other.</li>
<li><strong>Across domains, the offsets tell you how far each computer is from the broker computer.</strong> If you rely on NTP, all offsets should be within a few milliseconds. Large numbers mean NTP is not doing its job on that computer.</li>
<li>An offset shown as <strong><code>?</code></strong> means that agent has not measured anything yet. It may have just started, or it has measuring turned off.</li>
</ul>
<p>The <code>delay</code> column is the time the probe took to reach that agent and come back through the broker. It is naturally larger than the delay in the startup summary, and does not affect the offset shown.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is the only mode in which <code>mads top</code> sends something on the network instead of just listening. The probe is very light and harmless for the other agents.</p>
</div>
</div>
</section>
</section>
<section id="step-3-correct-the-timestamps-optional" class="level2">
<h2 class="anchored" data-anchor-id="step-3-correct-the-timestamps-optional">Step 3 — Correct the timestamps (optional)</h2>
<p>If you know that some computers’ clocks can’t be trusted, you can tell MADS to <strong>correct the timestamps</strong> using the measured offset. Add this line to the <code>[agents]</code> section of <code>mads.ini</code> (to apply it to all agents), or to the section of a single agent:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode ini code-with-copy"><code class="sourceCode ini"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">[agents]</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="dt">clock_correction </span><span class="ot">=</span><span class="st"> </span><span class="kw">true</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>From now on, when an agent sends a message, it adds its offset to its local time before writing <code>timestamp</code> and <code>timecode</code>. As a result, all messages carry <strong>the broker computer’s time</strong>, no matter which computer sent them.</p>
<p>A corrected message is always marked as such, so that you can tell it apart from an uncorrected one:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">{</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"data"</span><span class="fu">:</span> <span class="fu">{</span> <span class="dt">"T"</span><span class="fu">:</span> <span class="fl">21.4</span> <span class="fu">},</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"timestamp"</span><span class="fu">:</span> <span class="fu">{</span> <span class="dt">"$date"</span><span class="fu">:</span> <span class="st">"2025-07-11T10:53:18.758+0200"</span> <span class="fu">},</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"timecode"</span><span class="fu">:</span> <span class="fl">39198.72</span><span class="fu">,</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"hostname"</span><span class="fu">:</span> <span class="st">"raspberrypi"</span><span class="fu">,</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"clock_offset_us"</span><span class="fu">:</span> <span class="dv">42017</span><span class="fu">,</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"clock_ref"</span><span class="fu">:</span> <span class="st">"sensor_1:1"</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="fu">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl>
<dt><code>clock_offset_us</code></dt>
<dd>
The correction that was applied, in <strong>microseconds</strong> (millionths of a second). If you ever need the original local time, subtract it from <code>timestamp</code>. In the example, 10:53:18.758 − 42 ms = 10:53:18.716.
</dd>
<dt><code>clock_ref</code></dt>
<dd>
Which measurement was used, so that you can check that messages from different agents were corrected against the same reference.
</dd>
</dl>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Correction only helps if the agent can measure its offset. If an agent can’t reach the broker to measure, its messages are sent <strong>uncorrected</strong>, and in that case the <code>clock_offset_us</code> and <code>clock_ref</code> fields are missing. If you turn on correction, check for these fields in your data.</p>
</div>
</div>
</section>
<section id="keeping-up-with-drift" class="level2">
<h2 class="anchored" data-anchor-id="keeping-up-with-drift">Keeping up with drift</h2>
<p>By default, the offset is measured <strong>once, when the agent starts</strong>. For short experiments this is enough. For an agent that runs for days, the clocks keep drifting apart after the measurement: without NTP, typically by tens of milliseconds per hour.</p>
<p>To measure again periodically, set <code>clock_interval_ms</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode ini code-with-copy"><code class="sourceCode ini"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">[agents]</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="dt">clock_correction </span><span class="ot">=</span><span class="st"> </span><span class="kw">true</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="dt">clock_interval_ms </span><span class="ot">=</span><span class="st"> 60000   # measure again every minute</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Only one agent per clock domain actually measures again, and the others adopt its result. So even with many agents, this costs just a few tiny messages per minute.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Each new measurement makes the corrected time <strong>jump</strong> to the new value. In most cases the jump is a small fraction of a millisecond. After a long gap, or after the computer’s clock was changed by hand, it can be larger, and two consecutive messages can even appear slightly out of order. If your analysis is sensitive to this, keep <code>clock_interval_ms</code> short, so that each jump stays small.</p>
</div>
</div>
</section>
<section id="agents-that-cant-reach-the-broker-directly" class="level2">
<h2 class="anchored" data-anchor-id="agents-that-cant-reach-the-broker-directly">Agents that can’t reach the broker directly</h2>
<p>The measurement described in Step 1 uses the same connection that agents use to download their settings from the broker. Some agents don’t have that connection:</p>
<ul>
<li>agents on another network, connected through <code>mads-bridge</code> or <code>mads-federate</code></li>
<li>agents that load their settings from a <strong>local</strong> <code>.ini</code> file instead of from the broker (for example, started with <code>-s my_settings.ini</code>)</li>
</ul>
<p>For these agents, set:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode ini code-with-copy"><code class="sourceCode ini"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="dt">clock_source </span><span class="ot">=</span><span class="st"> "peer"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>With this setting, the agent measures its offset by exchanging messages with the <strong>other agents</strong> on the network, along the same path its data takes. Each answering agent also reports its own offset from the broker, so the final result still refers to the broker’s clock, reached in more than one step. The number of steps is reported as <code>hops</code> in the startup summary and in <code>mads top --probe</code>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Peer measurements go through the broker twice, so they are less precise than the direct ones: expect errors of a few milliseconds rather than fractions of a millisecond. They only work if at least one other agent on the network answers. Agents answer by default, as long as they subscribe to at least one topic. Also, the first peer measurement happens right after the agent connects, so its startup summary may still say <code>Clock offset: not yet measured</code>. Use <code>mads top --probe</code> to see the value.</p>
</div>
</div>
</section>
<section id="settings-reference" class="level2">
<h2 class="anchored" data-anchor-id="settings-reference">Settings reference</h2>
<p>All settings go in the <code>[agents]</code> section of <code>mads.ini</code> to apply to every agent, or in a single agent’s section to apply only to it. They are all optional. The values shown are the defaults.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode ini code-with-copy"><code class="sourceCode ini"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">[agents]</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="dt">clock_source </span><span class="ot">=</span><span class="st"> "broker"       # "broker", "peer", or "none"</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="dt">clock_sync_responder </span><span class="ot">=</span><span class="st"> true   # answer other agents' clock checks</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="dt">clock_interval_ms </span><span class="ot">=</span><span class="st"> 0         # 0 = measure only at startup</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="dt">clock_announce_ms </span><span class="ot">=</span><span class="st"> 5000      # how often to share the result with the same domain</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="dt">clock_correction </span><span class="ot">=</span><span class="st"> false      # apply the offset to timestamp/timecode</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Setting</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>clock_source</code></td>
<td><code>"broker"</code>: measure against the broker (most precise). <code>"peer"</code>: measure through other agents (see above). <code>"none"</code>: don’t measure at all.</td>
</tr>
<tr class="even">
<td><code>clock_sync_responder</code></td>
<td>Whether this agent answers clock checks from other agents and from <code>mads top --probe</code>, and shares its result with agents in the same domain. Leave it on unless you have a reason not to.</td>
</tr>
<tr class="odd">
<td><code>clock_interval_ms</code></td>
<td>How often, in milliseconds, to measure again. <code>0</code> means only once at startup.</td>
</tr>
<tr class="even">
<td><code>clock_announce_ms</code></td>
<td>How often, in milliseconds, each agent shares its offset with the other agents on the same computer.</td>
</tr>
<tr class="odd">
<td><code>clock_correction</code></td>
<td>If <code>true</code>, <code>timestamp</code> and <code>timecode</code> are corrected to the broker’s clock, and every message carries <code>clock_offset_us</code> and <code>clock_ref</code>.</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>v2.5.0 uses a special topic named <code>clocksync</code> for these exchanges. Don’t use that name for your own topics. Like the <code>control</code> and <code>agent_event</code> topics, it is automatically excluded from recordings made with <code>mads-record</code> and from <code>mads-federate</code>.</p>
</div>
</div>
</section>
</section>
<section id="which-setup-should-i-use" class="level1">
<h1>Which setup should I use?</h1>
<dl>
<dt>Everything runs on one computer</dt>
<dd>
Nothing to do: there is only one clock. <code>mads top --probe</code> will show a single domain with an offset close to zero.
</dd>
<dt>Several computers, all with working NTP</dt>
<dd>
Leave the defaults. Check with <code>mads top --probe</code> from time to time, and especially before an important experiment: all offsets should be within a few milliseconds. Leave <code>clock_correction</code> off, because NTP already does the job, and does it more smoothly.
</dd>
<dt>Isolated network, or computers you can’t configure</dt>
<dd>
Make sure the broker computer has a reasonably correct clock, ideally with NTP, or at least set carefully by hand. Then turn on correction and periodic measuring for the whole network:
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode ini code-with-copy"><code class="sourceCode ini"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">[agents]</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="dt">clock_correction </span><span class="ot">=</span><span class="st"> </span><span class="kw">true</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="dt">clock_interval_ms </span><span class="ot">=</span><span class="st"> </span><span class="dv">60000</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
All timestamps will be consistent with each other, even if the other computers’ clocks are off by minutes.
</dd>
<dt>Agents behind <code>mads-bridge</code> or <code>mads-federate</code></dt>
<dd>
Use <code>clock_source = "peer"</code> for those agents, as described <a href="#agents-that-cant-reach-the-broker-directly">above</a>.
</dd>
<dt>Brief sessions, where you only care about order within one agent’s data</dt>
<dd>
You can leave everything as is. Time differences <em>within</em> one agent’s messages are always reliable, because they come from a single clock.
</dd>
</dl>
</section>
<section id="good-to-know" class="level1">
<h1>Good to know</h1>
<ul>
<li><strong>MADS never changes your computer’s clock.</strong> It only measures, and, if you ask it to, corrects the times written in messages. NTP stays the right tool for keeping the system clock on time, and the two can work together.</li>
<li><strong>Accuracy.</strong> On a wired local network, the measured offset is typically accurate to a fraction of a millisecond. The method assumes a message takes the same time to go and to come back. When it doesn’t (busy Wi-Fi, a slow VPN), the error is up to half the difference between the two directions.</li>
<li><strong>Older brokers.</strong> An agent from v2.5.0 or later connected to an older broker simply can’t measure. The startup summary shows <code>Clock offset: not yet measured</code> and everything else works as before. However, agents and broker should in any case share the same <em>major.minor</em> version.</li>
<li><strong>Timecode offset.</strong> The startup summary also shows an older <code>Timecode offset</code> line. It is a single, coarse comparison with the broker, rounded to the timecode frame (40 ms at 25 fps). It is still there for compatibility, but the new <code>Clock offset</code> is far more precise.</li>
<li><strong>Sub-millisecond needs.</strong> If you need to align data to within microseconds (for example, vibration signals from different boards), you need hardware-level synchronization, such as PTP (IEEE 1588) or a shared trigger signal. That is beyond what software over a normal network can do, and beyond the scope of this guide.</li>
</ul>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mads-net\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Paolo Bosetti, <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">BY-NC-SA4.0</a></p>
</div>   
    <div class="nav-footer-center">

<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>